ARDUINOS:
  TOOLHEAD_ARDUINO_ID: "957363235323515012A2"
  FRAME_ARDUINO_ID: "957363235323514040C0"
  MM_PER_MOTOR_STEP: 0.14
  DISTANCE_BETWEEN_STARTING_LOCATION_AND_TRAY_CORNER_Y: 28
  DISTANCE_BETWEEN_STARTING_LOCATION_AND_TRAY_CORNER_X: 28
TRAYS:
  GAP_BETWEEN_TRAYS_IN_MM: 6
  LINK_TO_DENSE_TRAY_JSON: "sparse_tray.json"
  LINK_TO_SPARSE_TRAY_JSON: "dense_tray.json"